# These tests are general sanity checks of the unit testing mechanisms.

#####
# API(s) being tested: [test_condition][true]
##
# Expected end state:
# Tests that "assert true, return true" works (macros).
#####
{GENERIC_UNIT_TEST "test_assert" (
    [event]
        name = start
        {ASSERT ([true][/true])}
        {RETURN ([true][/true])}
    [/event]
)}

#####
# API(s) being tested: [test_condition][not][true]
##
# Expected end state:
# Tests that "assert false, return true" fails (macros).
#####
{GENERIC_UNIT_TEST "test_assert_fail" (
    [event]
        name = start
        {ASSERT ([not][true][/true][/not])}
        {RETURN ([true][/true])}
    [/event]
)}

#####
# API(s) being tested: unit_test.assert()
##
# Expected end state:
# Tests that "assert true, pass" works (lua).
#####
{GENERIC_UNIT_TEST "test_lua_assert" (
    [event]
        name = start
        [lua]
            code=<<
                unit_test.assert(true, 'assert true')
                unit_test.succeed()
            >>
        [/lua]
    [/event]
)}

#####
# API(s) being tested: unit_test.assert()
##
# Expected end state:
# Tests that "assert false, return true" works.
#####
{GENERIC_UNIT_TEST "test_lua_assert_fail" (
    [event]
        name = start
        [lua]
            code=<<
                unit_test.assert(false, 'assert false')
                unit_test.succeed()
            >>
        [/lua]
    [/event]
)}

#####
# API(s) being tested: unit_test.fail(),[fire_event]
##
# Expected end state:
# A fail() in a fired event causes the test to fail.
#####
{GENERIC_UNIT_TEST "test_lua_assert_fail_in_fired_event" (
    [event]
        id = fail_event
        [lua]
            code=<<
                unit_test.fail()
            >>
        [/lua]
    [/event]
    [event]
        name = start
        [fire_event]
            id = fail_event
        [/fire_event]
        [lua]
            code=<<
                unit_test.succeed()
            >>
        [/lua]
    [/event]
)}

#####
# API(s) being tested: unit_test.assert_equal(),unit_test.assert_not_equal(),unit_test.assert_greater(),unit_test.assert_less(),unit_test.assert_in_range(),unit_test.assert_approx_equal(),unit_test.assert_contains()
##
# Expected end state:
# All string and numeric comparison assertions succeed.
#####
{GENERIC_UNIT_TEST "test_lua_assert_compare" (
    [event]
        name=start
        [lua]
            code=<<
                unit_test.assert_equal('foo', 'foo', 'string equality')
                unit_test.assert_not_equal('foo', 'bar', 'string inequality')
                unit_test.assert_greater('foo', 'bar', 'string ordering')
                unit_test.assert_equal(1, 1, 'numeric equality')
                unit_test.assert_not_equal(1, 2, 'numeric inequality')
                unit_test.assert_greater(2, 1, 'numeric greater-than')
                unit_test.assert_less(1, 2, 'numeric less-than')
                unit_test.assert_in_range(1, 0, 2, 'numeric in-range')
                unit_test.assert_approx_equal(1, 1.0001, 0.001, 'numeric approx-equal')
                unit_test.assert_contains('abcdef', 'bc', 'substring')
                unit_test.succeed()
            >>
        [/lua]
    [/event]
)}

#####
# API(s) being tested: unit_test.assert_equal()
##
# Expected end state:
# The assert successfully fails.
#####
{GENERIC_UNIT_TEST "test_lua_assert_compare_fail1" (
    [event]
        name=start
        [lua]
            code=<<
                unit_test.assert_equal('foo', 'bar', 'string equality')
                unit_test.succeed()
            >>
        [/lua]
    [/event]
)}

#####
# API(s) being tested: unit_test.assert_not_equal()
##
# Expected end state:
# The assert successfully fails.
#####
{GENERIC_UNIT_TEST "test_lua_assert_compare_fail2" (
    [event]
        name=start
        [lua]
            code=<<
                unit_test.assert_not_equal('foo', 'foo', 'string inequality')
                unit_test.succeed()
            >>
        [/lua]
    [/event]
)}

#####
# API(s) being tested: unit_test.assert_less()
##
# Expected end state:
# The assert successfully fails.
#####
{GENERIC_UNIT_TEST "test_lua_assert_compare_fail3" (
    [event]
        name=start
        [lua]
            code=<<
                unit_test.assert_less('foo', 'bar', 'string ordering')
                unit_test.succeed()
            >>
        [/lua]
    [/event]
)}

#####
# API(s) being tested: unit_test.assert_equal()
##
# Expected end state:
# The assert successfully fails.
#####
{GENERIC_UNIT_TEST "test_lua_assert_compare_fail4" (
    [event]
        name=start
        [lua]
            code=<<
                unit_test.assert_equal(1, 2, 'numeric equality')
                unit_test.succeed()
            >>
        [/lua]
    [/event]
)}

#####
# API(s) being tested: unit_test.assert_not_equal()
##
# Expected end state:
# The assert successfully fails.
#####
{GENERIC_UNIT_TEST "test_lua_assert_compare_fail5" (
    [event]
        name=start
        [lua]
            code=<<
                unit_test.assert_not_equal(1, 1, 'numeric inequality')
                unit_test.succeed()
            >>
        [/lua]
    [/event]
)}

#####
# API(s) being tested: unit_test.assert_greater()
##
# Expected end state:
# The assert successfully fails.
#####
{GENERIC_UNIT_TEST "test_lua_assert_compare_fail6" (
    [event]
        name=start
        [lua]
            code=<<
                unit_test.assert_greater(1, 2, 'numeric greater-than')
                unit_test.succeed()
            >>
        [/lua]
    [/event]
)}

#####
# API(s) being tested: unit_test.assert_less()
##
# Expected end state:
# The assert successfully fails.
#####
{GENERIC_UNIT_TEST "test_lua_assert_compare_fail7" (
    [event]
        name=start
        [lua]
            code=<<
                unit_test.assert_less(2, 1, 'numeric less-than')
                unit_test.succeed()
            >>
        [/lua]
    [/event]
)}

#####
# API(s) being tested: unit_test.assert_in_range()
##
# Expected end state:
# The assert successfully fails.
#####
{GENERIC_UNIT_TEST "test_lua_assert_compare_fail8" (
    [event]
        name=start
        [lua]
            code=<<
                unit_test.assert_in_range(1, 2, 5, 'numeric in-range')
                unit_test.succeed()
            >>
        [/lua]
    [/event]
)}

#####
# API(s) being tested: unit_test.assert_approx_equal()
##
# Expected end state:
# The assert successfully fails.
#####
{GENERIC_UNIT_TEST "test_lua_assert_compare_fail9" (
    [event]
        name=start
        [lua]
            code=<<
                unit_test.assert_approx_equal(1, 1.001, 0.0001, 'numeric approx-equal')
                unit_test.succeed()
            >>
        [/lua]
    [/event]
)}

#####
# API(s) being tested: unit_test.assert_nothrow()
##
# Expected end state:
# No error is thrown.
#####
{GENERIC_UNIT_TEST "test_lua_assert_errors1" (
    [event]
        name=start
        [lua]
            code=<<
                unit_test.assert_nothrow(function() end, 'no error')
                unit_test.succeed()
            >>
        [/lua]
    [/event]
)}

#####
# API(s) being tested: unit_test.assert_nothrow()
##
# Expected end state:
# An error is thrown.
#####
{GENERIC_UNIT_TEST "test_lua_assert_errors2" (
    [event]
        name=start
        [lua]
            code=<<
                unit_test.assert_nothrow(function() error('error') end, 'no error')
                unit_test.succeed()
            >>
        [/lua]
    [/event]
)}

#####
# API(s) being tested: unit_test.assert_throws()
##
# Expected end state:
# No error is thrown.
#####
{GENERIC_UNIT_TEST "test_lua_assert_errors3" (
    [event]
        name=start
        [lua]
            code=<<
                unit_test.assert_throws(function() end, 'any error')
                unit_test.succeed()
            >>
        [/lua]
    [/event]
)}

#####
# API(s) being tested: unit_test.assert_throws()
##
# Expected end state:
# An error is thrown.
#####
{GENERIC_UNIT_TEST "test_lua_assert_errors4" (
    [event]
        name=start
        [lua]
            code=<<
                unit_test.assert_throws(function() error('error') end, 'any error')
                unit_test.succeed()
            >>
        [/lua]
    [/event]
)}

#####
# API(s) being tested: unit_test.assert_throws_with()
##
# Expected end state:
# The expected error is not thrown.
#####
{GENERIC_UNIT_TEST "test_lua_assert_errors5" (
    [event]
        name=start
        [lua]
            code=<<
                unit_test.assert_throws_with('error', function() end, 'specific error')
                unit_test.succeed()
            >>
        [/lua]
    [/event]
)}

#####
# API(s) being tested: unit_test.assert_throws_with()
##
# Expected end state:
# The expected error is thrown.
#####
{GENERIC_UNIT_TEST "test_lua_assert_errors6" (
    [event]
        name=start
        [lua]
            code=<<
                unit_test.assert_throws_with('error', function() error('error', 0) end, 'specific error')
                unit_test.succeed()
            >>
        [/lua]
    [/event]
)}

#####
# API(s) being tested: unit_test.assert_throws_with()
##
# Expected end state:
# The expected error is not thrown.
#####
{GENERIC_UNIT_TEST "test_lua_assert_errors7" (
    [event]
        name=start
        [lua]
            code=<<
                unit_test.assert_throws_with('error', function() error('foo', 0) end, 'specific error')
                unit_test.succeed()
            >>
        [/lua]
    [/event]
)}

#####
# API(s) being tested: unit_test.assert_throws_with()
##
# Expected end state:
# The expected error is thrown.
#####
{GENERIC_UNIT_TEST "test_lua_assert_errors8" (
    [event]
        name=start
        [lua]
            code=<<
                unit_test.assert_throws_with('error', function() error('error') end, 'specific error')
                unit_test.succeed()
            >>
        [/lua]
    [/event]
)}

#####
# API(s) being tested: unit_test.assert_throws_with()
##
# Expected end state:
# The expected error is not thrown.
#####
{GENERIC_UNIT_TEST "test_lua_assert_errors9" (
    [event]
        name=start
        [lua]
            code=<<
                unit_test.assert_throws_with('error', function() error('foo') end, 'specific error')
                unit_test.succeed()
            >>
        [/lua]
    [/event]
)}
